Alu
CPUlm/CPUlm pull request #3
Opened 2023-12-23 17:47 UTC by vinc42

division et flags

2023-12-24 13:18 UTC, hgruniaux requested changes

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +        r = r | a[i]
Les indices sont vraiment indexés à partir de 1 ??

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +
Il y a beaucoup de lignes vides, c'est normal ?

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +    # TODO reflechir a la division signee
Ca serait cool, si possible, de mettre un commentaire expliquant dans les grandes lignes l'algorithme de DIVISION. Au du moins un lien vers un site internet que tu as utilisé comme référence (si tu en as utilisé un).

Par exemple, je vois pas trop comme en direct pourquoi tu utilise un OR dans la boucle et un incr

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +        neg_div,_ = incr(~diviseur[0:i+1])
Je suppose que ce OR puis INCR sert à prendre la négation. Peut -être crée une fonction negate() qui fait ces deux opérations. Ca sera plus clair dans le code, et on pourra la réutiliser ailleurs. Tu en penses quoi ?

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +    rs2_neg,rs2_neg_carry = incr(~rs2)
Peut être utilisé une fonction negate() au lieu de incr(~)

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +                                  Constant("1"), # TODO
Ce TODO correspond à quoi ?

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +    new_flags = (flag_z, flag_n, flag_c, flag_z )
Il y a deux fois le FLAG_Z, c'est normal ?

2023-12-24 13:18 UTC, hgruniaux commented on src/alu.py
> +                                  rs2_neg_carry | (signe_rs1 ^ signe_rs2_neg) | ((~signe_rs1)^signe_rd),
Toutes ces opérations binaires sont un peu obscures pour moi x)

2023-12-24 13:18 UTC, hgruniaux commented
Aussi JOYEUX NOEL (en avance) !

2023-12-27 17:18 UTC, vinc42 commented on src/alu.py
> +        r = r | a[i]
l'indice 0 est fait par la ligne 33

2023-12-27 17:18 UTC, vinc42 commented on src/alu.py
> +    # TODO reflechir a la division signee
je vais ajouter ça

2023-12-27 17:19 UTC, vinc42 commented on src/alu.py
> +        neg_div,_ = incr(~diviseur[0:i+1])
bonne idée, merci

2023-12-27 17:20 UTC, vinc42 commented on src/alu.py
> +                                  Constant("1"), # TODO
ce qui m'inquiete c'est qu'il y a un TODO ici et pas dans mon code...

2023-12-27 17:21 UTC, vinc42 commented on src/alu.py
> +    new_flags = (flag_z, flag_n, flag_c, flag_z )
oups... Merci

2023-12-27 17:44 UTC, vinc42 commented
J'ai corrigé tout ça dans le dernier commit.

2023-12-27 20:50 UTC, hgruniaux approved these changes

2023-12-27 20:51 UTC, merged